### ISSUE TITLE
favicon is pixelated

### ISSUE THREAD

**Issue by fharper** [hakuwo/Torimodosu#4]
The favicon is pixelated, at least on Google Chrome 116.0.5845.110 on macOS (Ventura) 13.4.1 build 22F770820d.

<img width="43" alt="CleanShot 2023-08-28 at 17 26 10@2x" src="https://github.com/hakuwo/Torimodosu/assets/1170989/5e43aa19-21dd-4ff3-b60d-2a10957876d3">

**Comment by hakuwo** [comment]
Thank you for the report.
I'll try to come up with a solution to this.

**Comment by hakuwo** [comment]
@fharper 
I have improved the favicon's image quality of favicon by this commit.
9b5fd74

![favicon_9b5fd74](https://github.com/hakuwo/Torimodosu/assets/47149566/c684bbfd-bebd-4491-88a5-4d7c8d1ff85e)
(Google Chrome 116.0.5845.111 on Windows10 version 22H2 build 19045.3324)

**Comment by fharper** [comment]
Perfect, I loaded it unpacked, and it's fixed, thanks!
